import { useState } from 'react';
import { motion } from 'framer-motion';
import ReactMarkdown from 'react-markdown';
import remarkGfm from 'remark-gfm';
import { Copy, Check, FileDown, RefreshCw, Share2 } from 'lucide-react';

export default function ResultCard({ answer, question, onRegenerate }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = async () => {
    await navigator.clipboard.writeText(answer);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  const handleExportPDF = () => {
    const printWindow = window.open('', '_blank');
    printWindow.document.write(`
      <!DOCTYPE html>
      <html>
      <head>
        <title>AI Analysis - ${question || 'Document'}</title>
        <style>
          body { font-family: 'Segoe UI', Arial, sans-serif; max-width: 800px; margin: 40px auto; padding: 0 20px; color: #111827; line-height: 1.7; }
          h1 { font-size: 20px; color: #2563EB; border-bottom: 2px solid #2563EB; padding-bottom: 8px; }
          .meta { color: #64748b; font-size: 13px; margin-bottom: 24px; }
          .question { background: #f1f5f9; padding: 12px 16px; border-radius: 8px; border-left: 3px solid #2563EB; margin-bottom: 20px; font-style: italic; }
          .answer { white-space: pre-wrap; }
          .footer { margin-top: 40px; padding-top: 16px; border-top: 1px solid #e2e8f0; color: #94a3b8; font-size: 11px; text-align: center; }
          @media print { body { margin: 20px; } }
        </style>
      </head>
      <body>
        <h1>AI Document Analysis</h1>
        <div class="meta">Generated on ${new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric', hour: '2-digit', minute: '2-digit' })}</div>
        ${question ? `<div class="question"><strong>Question:</strong> ${question}</div>` : ''}
        <div class="answer">${answer.replace(/\n/g, '<br>')}</div>
        <div class="footer">Generated by InsightRAG</div>
      </body>
      </html>
    `);
    printWindow.document.close();
    printWindow.print();
  };

  const handleShare = async () => {
    if (navigator.share) {
      await navigator.share({ title: 'AI Analysis', text: answer });
    } else {
      await navigator.clipboard.writeText(answer);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    }
  };

  const actions = [
    { icon: copied ? Check : Copy, label: copied ? 'Copied!' : 'Copy', onClick: handleCopy },
    { icon: FileDown, label: 'Export PDF', onClick: handleExportPDF },
    { icon: RefreshCw, label: 'Regenerate', onClick: onRegenerate },
    { icon: Share2, label: 'Share', onClick: handleShare },
  ];

  return (
    <motion.div
      initial={{ opacity: 0, y: 20, scale: 0.98 }}
      animate={{ opacity: 1, y: 0, scale: 1 }}
      transition={{ duration: 0.4, ease: [0.25, 0.46, 0.45, 0.94] }}
      className="w-full rounded-2xl bg-white dark:bg-slate-800/50 border border-slate-200/50 dark:border-slate-700/50 shadow-sm overflow-hidden"
    >
      {/* Header */}
      <div className="px-6 py-4 border-b border-slate-100 dark:border-slate-700/50 flex flex-col sm:flex-row sm:items-center justify-between gap-2">
        <div className="min-w-0">
          <h3 className="text-sm font-semibold text-slate-900 dark:text-white">AI Response</h3>
          {question && (
            <p className="text-xs text-slate-400 mt-0.5 truncate max-w-md">Q: {question}</p>
          )}
        </div>
        <div className="flex items-center gap-1 flex-shrink-0">
          {actions.map((action) => (
            <motion.button
              key={action.label}
              whileHover={{ scale: 1.05 }}
              whileTap={{ scale: 0.95 }}
              onClick={action.onClick}
              className="px-3 py-1.5 rounded-lg text-xs font-medium text-slate-600 dark:text-slate-300 hover:bg-slate-100 dark:hover:bg-slate-700 transition-colors flex items-center gap-1.5"
              title={action.label}
            >
              <action.icon className="w-3.5 h-3.5" />
              <span className="hidden sm:inline">{action.label}</span>
            </motion.button>
          ))}
        </div>
      </div>

      {/* Content */}
      <div className="px-6 py-5">
        <div className="markdown-body text-sm text-slate-700 dark:text-slate-300 leading-relaxed">
          <ReactMarkdown remarkPlugins={[remarkGfm]}>{answer}</ReactMarkdown>
        </div>
      </div>
    </motion.div>
  );
}
