import { getSovereignDB } from '../backend/storage/sovereignDB.js';
import { classifier } from '../backend/models/classifier.js';
import { taskGate, buildPlan, routeWorkflow } from '../backend/agents/taskRouter.js';
import { policy } from '../backend/security/policy.js';
import { sovereignSearch, querySovereign } from '../backend/rag/sovereignPipeline.js';
import { generateDocx, saveArtifact } from '../backend/artifacts/index.js';
import { seedSovereign } from './demo-seed.js';

const USER = { id: 'demo-operator', email: 'operator@plant.local', name: 'Demo Operator', role: 'inspector' };
const fmt = (n) => (n ?? 0).toLocaleString('en-IN');
const line = (label, value, pad = 32) => `  ${String(label).padEnd(pad)} ${value}`;

async function main() {
  console.log('=== Sovereign AI Workbench — deterministic demo ===\n');

  console.log('[1/7] Seed documents into local SQLite + hybrid vector store');
  const db = getSovereignDB();
  const seed = await seedSovereign();
  for (const r of seed) console.log(line(r.filename, r.skipped ? 'already ingested' : `ingested · ${r.chunks} chunks · ${r.embeddingProvider}`));

  console.log('\n[2/7] Offline task classification (auditable, no model needed)');
  const samples = [
    'Draft an approval note for B-101 bearing spares above the maintenance limit',
    'Find the LOTO isolation checks for work on blower B-101',
    'Write a Python script that parses the vibration CSV and flags alarms',
  ];
  for (const q of samples) {
    const c = classifier.classify({ question: q });
    console.log(line(`"${q.slice(0, 46)}..."`, `${c.taskType} (${c.modality}) — ${c.reason}`));
  }

  console.log('\n[3/7] Human-in-the-loop gating (policy risk scan of the free text)');
  const approvalQ = samples[0];
  const risk = policy().riskFor({ input: approvalQ, taskType: 'approval_note', classification: 'INTERNAL', domain: '' });
  const gate = taskGate({ input: approvalQ, classification: { taskType: 'approval_note', classification: 'INTERNAL' }, user: USER });
  console.log(line('risk level', risk.risk, 28));
  console.log(line('requiresApproval', String(gate.requiresApproval), 28));
  console.log(line('workflow', routeWorkflow('approval_note'), 28));
  console.log(line('current user role', gate.userRole, 28));
  console.log('  plan steps: ' + buildPlan('approval_note', gate).steps.map(s => s.step).join(' → '));

  console.log('\n[4/7] Grounded retrieval (access-scoped semantics, BM25 + cosine + MMR)');
  const searchQ = 'What is the preventive maintenance frequency for B-101 bearing greasing?';
  const search = await sovereignSearch({ question: searchQ, user: USER, topK: 3 });
  for (const r of search.results) console.log(line(`score ${r.score.toFixed(3)}`, `${r.document} · page ${r.page}`, 32));

  console.log('\n[5/7] Honest generation boundary (no local model → no fabricated answer)');
  const query = await querySovereign({ question: searchQ, user: USER });
  console.log(line('retrieved sources', `${query.sources.length} passages`, 28));
  console.log(line('confidence', query.confidence, 28));
  console.log(line('generation', !query.generationBlocked ? 'model available' : query.answer ? `${query.answer.slice(0, 90)}…` : 'blocked (honest)', 28));

  console.log('\n[6/7] Artifact layer works independently of inference');
  const { doc, packer } = await generateDocx({
    title: 'Demo — Workbench Packet',
    meta: { Request: approvalQ, 'Generated by': 'Sovereign Workbench (local)' },
    sections: [
      { heading: 'Sources', bullets: search.results.map(r => `${r.document} (page ${r.page}, score ${r.score.toFixed(3)})`) },
      { heading: 'Plan', bullets: buildPlan('approval_note', gate).steps.map(s => `${s.step}: ${s.note}`) },
    ],
  });
  const docxBuffer = await packer.toBuffer(doc);
  const art = await saveArtifact({
    taskId: 'demo-0000', userId: USER.id, name: 'demo-workbench-packet.docx', type: 'docx', mime: 'application/vnd.openxmlformats-officedocument.wordprocessingml.document', buffer: docxBuffer,
  });
  console.log(line('artifact', `${art.name} · ${art.checksum.slice(0, 12)}… · ${(art.size / 1024).toFixed(1)} KB`, 28));

  console.log('\n[7/7] Tamper-evident audit trail');
  const verify = db.verifyAuditChain();
  const entries = db.listAudit({ limit: 50 });
  const counts = entries.reduce((acc, e) => { acc[e.category] = (acc[e.category] || 0) + 1; return acc; }, {});
  console.log(line('hash chain', `${verify.intact ? 'INTACT' : 'BROKEN '} (${verify.count} entries)`, 28));
  console.log(line('categories', JSON.stringify(counts), 28));

  console.log('\nDone. Start the workbench UI on the server and open /workbench.');
}

main().catch((err) => { console.error('Demo failed:', err); process.exit(1); });